using Renee.Domain.Enums;

namespace Renee.Application.Services.Administration.ImportCsvData;

public class ParsedCsvData
{
	public int LineNumber { get; set; }
	public string? ExternalReference { get; set; }
	public DateTime? FirstEncounterDate { get; set; }
	public DateTime? StartOfAccompanyingDate { get; set; }
	public DateTime? OpeningDate { get; set; }
	public DateTime? CloseDate { get; set; }
	public DateTime? EndOfAccompanyingDate { get; set; }
	public DateTime? EndOfEncounterDate { get; set; }
	public bool? ZeroEnergyExclusionTerritoriesProgram { get; set; }
	public AccompanyingType? AccompanyingType { get; set; }
	public string? AccompanyingFileTerritory { get; set; }
	public HouseholdTypology? HouseholdTypology { get; set; }
	public bool? IsFollowedByAnSocialWorker { get; set; }
	public bool? HasAnOccupantWithDisabilities { get; set; }
	public bool? HasAnOccupantWithLongTermIllness { get; set; }
	public bool? HasAnOccupantWithIndependenceLoss { get; set; }
	public bool? HasAnOccupantUnderGuardianship { get; set; }
	public bool? HasAnOccupantUnderCuratorship { get; set; }
	public double? ReferenceIncomeTax { get; set; }
	public string? SocialContext { get; set; }
	public string? HouseholdProject { get; set; }
	public string? HouseholdAvailabilityForVisits { get; set; }
	public string? CommentsOnHouseholdDifficulties { get; set; }
	public bool? HasOverdueInvoice { get; set; }
	public string? HouseholdDifficulties { get; set; }
	public string? HouseholdExpenses { get; set; }
	public string? HouseholdResources { get; set; }
	public DateTime? Birthdate { get; set; }
	public SocioProfessionalCategory? SocioProfessionalCategory { get; set; }
	public string? PhoneNumber { get; set; }
	public string? Email { get; set; }
	public string? Profession { get; set; }
	public SocialProtectionFund? SocialProtectionFund { get; set; }
	public string? CommentOnSocialProtectionFund { get; set; }
	public PensionFund? PensionFundOccupant { get; set; }
	public string? CommentOnPensionFund { get; set; }
	public AdditionalFund? AdditionnalFund { get; set; }
	public string? CommentOnAdditionnalFund { get; set; }
	public string? FirstName { get; set; }
	public string? LastName { get; set; }
	public GeographicalHousingAreaTypology? GeographicAreaTypology { get; set; }
	public bool? IsInABFArea { get; set; }
	public string? ArchitecturalNorms { get; set; }
	public OwnershipStatus? OwnershipStatus { get; set; }
	public HousingType? HousingType { get; set; }
	public HousingYearConstruction? ConstructionYear { get; set; }
	public double? LivingSpace { get; set; }
	public int? NumberOfRoom { get; set; }
	public int? NumberOfFloor { get; set; }
	public int? YearOfAcquisitionOrEntry { get; set; }
	public string? CadastralReference { get; set; }
	public SunExposure? SunExposure { get; set; }
	public int? NumberOfDoor { get; set; }
	public int? NumberOfWindow { get; set; }
	public int? NumberOfPatioDoor { get; set; }
	public int? NumberOfRoofDoor { get; set; }
	public int? NumberOfBayWindow { get; set; }
	public double? CeilingHeight { get; set; }
	public bool? HasPreviousWork { get; set; }
	public string? CommentOnPreviousWork { get; set; }
	public string? Label { get; set; }
	public string? PostalCode { get; set; }
	public string? City { get; set; }
	public string? Department { get; set; }
	public string? Region { get; set; }
	public string? AdditionnalComment { get; set; }
	public DegradationIndex? DegradationIndex { get; set; }
	public UnsanitaryCoefficient? UnsanitaryCoefficient { get; set; }
	public EnergyDeprivation? EnergyDepravation { get; set; }
	public ComfortLevel? SummerThermalComfortLevel { get; set; }
	public ComfortLevel? WinterThermalComfortLevel { get; set; }
	public ComfortLevel? NoiseComfortLevel { get; set; }
	public bool? HasPestOrMold { get; set; }
	public bool? HasFaultyElectricalSystem { get; set; }
	public bool? HasVentilationSystem { get; set; }
	public bool? HasHeatingSystem { get; set; }
	public bool? HasHotWaterProduction { get; set; }
	public bool? RoofingState { get; set; }
	public bool? HasOpenings { get; set; }
	public bool? HasHousingCover { get; set; }
	public string? DisordersObservedCommentary { get; set; }
	public DpeLabel? Dpe { get; set; }
	public GesLabel? Ges { get; set; }
	public double? AnnualEnergyConsumption { get; set; }
	public double? AnnualGesEmission { get; set; }
	public string? HeatingEnergy { get; set; }
	public DpeLabel? EstimatedDpeAfterWork { get; set; }
	public double? EstimatedAnnualEnergyConsumptionAfterWork { get; set; }
	public double? EstimatedAnnualGesEmissionsAfterWork { get; set; }
	public GesLabel? EstimatedGesAfterWork { get; set; }
	public RenovationType? RenovationType { get; set; }
	public string? NextStepAndVigilancePoint { get; set; }
	public bool? HasInterestInPossibleARAProcess { get; set; }
	public bool? HasNeedForTemporaryReHousing { get; set; }
	public bool? HasEmergencyWorks { get; set; }
	public bool? HasEnergeticsRenovationWorks { get; set; }
	public bool? HasInducedWorks { get; set; }
	public bool? HasSafetyAndHealthWorks { get; set; }
	public PartlyStateTreatment? TreatedAirTightness { get; set; }
	public PartlyStateTreatment? TreatedThermalBridge { get; set; }
	public PartlyStateTreatment? AreExistingHumidityAndVaporMigrationManagedAfterTreatment { get; set; }
	public bool? IsHouseholdReadyToStartARAProcess { get; set; }
	public bool? AreHouseholdPhysicalCapacitiesTakenIntoAccount { get; set; }
	public bool? DoHouseholdCanMobilizeSocialCircleOnConstructionSite { get; set; }
	public string? WorkDetails { get; set; }
	public string? HouseholdAvailabilitiyToOrganizeARASite { get; set; }
	public bool? IsRgeLabelUpToDate { get; set; }
	public string? OtherQualification { get; set; }
	public string? ProjectType { get; set; }
	public string? InsuranceType { get; set; }
	public double? MaPrimeRenovGuidedPath { get; set; }
	public double? MaPrimeRenovCoOwnerShip { get; set; }
	public double? MaPrimeLogementDecent { get; set; }
	public double? MaPrimeAdapt { get; set; }
	public double? BonusForExitingEnergeticSieve { get; set; }
	public double? RegionalAids { get; set; }
	public double? DepartmentalAids { get; set; }
	public double? PublicEstablishmentsForInterCommunalCooperationAids { get; set; }
	public double? MunicipalityAids { get; set; }
	public string? SolicitedBankLoanType { get; set; }
	public double? ClassicBankLoan { get; set; }
	public double? MdphFinancing { get; set; }
	public double? CeeFinancing { get; set; }
	public double? CafMsaFinancing { get; set; }
	public double? PensionFund { get; set; }
	public double? UnderprivilegedHousingFoundation { get; set; }
	public double? LeroyMerlinFoundation { get; set; }
	public double? WattForChangeFoundation { get; set; }
	public double? SocialProtectionGroup { get; set; }
	public double? HouseholdMaximumSavingAmountForRenovationProject { get; set; }
	public double? OtherFamilyMemberMaximumSupportAmountForRenovationProject { get; set; }
	public string? FundingModeLabel { get; set; }
	public double? AccompanyingCost { get; set; }
	public double? HouseholdSelfFinancing { get; set; }
	public string? IntermediateAirtightnessTestResult { get; set; }
	public string? JustificationAndActionsPutInPlaceIfNoTest { get; set; }
	public bool? HasEffectiveComplianceWithWorkRecommendations { get; set; }
	public bool? HasWorksEnabledHouseholdToStayAtHome { get; set; }
	public int? WellBeingRating { get; set; }
	public int? EducationalFrameworkRating { get; set; }
	public int? FamilySatisfaction { get; set; }
	public bool? ReturnToEmployment { get; set; }
	public bool? HasHousingAdaptationWorks { get; set; }
	public bool? HasFinishingWorks { get; set; }
	public bool? HasSafetyWorks { get; set; }
	public bool? HasPreparationWorks { get; set; }
	public bool? HasEmergencyWorksMonitoring { get; set; }
	public bool? HasUnsanitaryExit { get; set; }
	public PartlyStateTreatment? TreatedAirTightnessWorks { get; set; }
	public PartlyStateTreatment? TreatedThermalBridgesWorks { get; set; }
	public bool? HasHumidityManagement { get; set; }
	public double? WorkTotalCost { get; set; }
	public string? SolidarBuilder { get; set; }
	public MarkerNature? MarkerNature { get; set; }
	public string? CommentOnMarkerNature { get; set; }
	public bool? IsDeleted { get; set; }
	public AccompanyingTimeDuration? AccompanyingTimeDurationForIdentificationMilestone { get; set; }
	public AccompanyingTimeDuration? AccompanyingTimeDurationForOrganizeAndFinanceMilestone { get; set; }
	public AccompanyingTimeDuration? AccompanyingTimeDurationForRealizeAndFollowMilestone { get; set; }
	public int? NumberOfOccupants { get; set; }
	public double? MonthlyEnergeticsExpenses { get; set; }
	public double? StopEnergyExclusionFunds { get; set; }
}